apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: service-test
  name: service-test
  namespace: my-workspace   # TODO 名称空间
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: service-test # TODO 应用名
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-test # TODO 应用名
    spec:
      imagePullSecrets:
        - name: aliyun-docker-hub  # TODO 提前在项目下配置访问阿里云的账号密码
      containers:
        - image: registry.cn-hangzhou.aliyuncs.com/zhengqingya/springboot-demo:$BUILD_NUMBER # TODO 镜像
          #          readinessProbe:
          #            httpGet:
          #              path: /actuator/health
          #              port: 8080
          #            timeoutSeconds: 10
          #            failureThreshold: 30
          #            periodSeconds: 5
          imagePullPolicy: Always
          name: app
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: service-test # TODO 应用名
  name: service-test # TODO 应用名
  namespace: my-workspace # TODO 名称空间
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-test # TODO 应用名
  sessionAffinity: None
  type: ClusterIP